<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net6.0</TargetFramework>
    <RollForward>Major</RollForward>
    <MonoGamePlatform>DesktopGL</MonoGamePlatform>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="MonoGame.Content.Builder.Task" Version="3.8.1.303" />
  </ItemGroup>

</Project>
